return {
	'nvim-treesitter/nvim-treesitter', branch = 'main',
	lazy = false,
	build = ':TSUpdate',
    config = function()
        -- Installs if not present (else no-op)
        require('nvim-treesitter').install({
            'bash',
            'c',
            'css',
            'desktop',
            'dockerfile',
            'gitcommit',
            'gitignore',
            'html',
            'htmldjango',
            'javascript',
            'jinja',
            'json',
            'jsx',
            'lua',
            'luadoc',
            'markdown',
            'markdown_inline',
            'nginx',
            'php',
            'python',
            'query',
            'scss',
            'sql',
            'tsx',
            'typescript',
            'rust',
            'vim',
            'vimdoc',
            'yaml',
        })
    end,
}
